CREATE TABLE USERS
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(32) UNIQUE NOT NULL,
    PASSWORD VARCHAR            NOT NULL
);

CREATE TABLE COURSES
(
    ID   VARCHAR(15) PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL
);

CREATE TABLE USER_COURSE_REGISTRATIONS
(
    PRIMARY KEY (USER_ID, COURSE_ID),
    USER_ID   INTEGER     NOT NULL REFERENCES USERS (ID),
    COURSE_ID VARCHAR(32) NOT NULL REFERENCES COURSES (ID),
    ADMIN     BOOLEAN     NOT NULL

);

CREATE TABLE BOOKING_LISTS
(
    ID          SERIAL PRIMARY KEY,
    COURSE_ID   VARCHAR(32) NOT NULL REFERENCES COURSES (ID),
    USER_ID     INTEGER     NOT NULL REFERENCES USERS (ID),
    DESCRIPTION VARCHAR(64) NOT NULL,
    LOCATION    VARCHAR(32) NOT NULL,
    TIME        TIMESTAMP   NOT NULL,
    INTERVAL    INTEGER     NOT NULL,
    MAX_SLOTS   INTEGER     NOT NULL
);

CREATE TABLE RESERVATIONS
(
    ID          SERIAL PRIMARY KEY,
    LIST_ID     INTEGER NOT NULL REFERENCES BOOKING_LISTS (ID),
    USER_ID     INTEGER NOT NULL REFERENCES USERS (ID),
    SEQUENCE_ID INTEGER NOT NULL
);